export const hotelRooms = [
  {
    id: 1,
    name: 'Стандартний номер',
    description:
      'Затишний номер з двоспальним ліжком, телевізором та кондиціонером.',
    pricePerNight: 1200,
    maxGuests: 2,
    amenities: ['Wi-Fi', 'Телевізор', 'Кондиціонер', 'Мінібар'],
    images: ['room1.jpg'],
    availability: true,
    rating: 4.5,
    reviews: [
      { user: 'Олександр', comment: 'Чисто і комфортно', rating: 4 },
      { user: 'Марія', comment: 'Гарне розташування', rating: 5 },
    ],
    availableDates: ['2024-11-23', '2024-11-24', '2024-11-25'],
  },
  {
    id: 2,
    name: 'Люкс з видом на море',
    description: 'Просторий номер з великим балконом і чудовим видом на море.',
    pricePerNight: 2500,
    maxGuests: 4,
    amenities: ['Wi-Fi', 'Телевізор', 'Балкон', 'Джакузі', 'Кондиціонер'],
    images: ['room2.jpg'],
    availability: true,
    rating: 4.8,
    reviews: [
      { user: 'Анна', comment: 'Вражаючий вид з вікна!', rating: 5 },
      { user: 'Ігор', comment: 'Прекрасний сервіс', rating: 5 },
    ],
    availableDates: ['2024-11-24', '2024-11-25', '2024-11-26'],
  },
  {
    id: 3,
    name: 'Одномісний економ',
    description: 'Компактний номер для одного гостя з базовими зручностями.',
    pricePerNight: 700,
    maxGuests: 1,
    amenities: ['Wi-Fi', 'Телевізор'],
    images: ['room3.jpg'],
    availability: true,
    rating: 4.0,
    reviews: [
      { user: 'Юлія', comment: 'Дешево і практично', rating: 4 },
      { user: 'Дмитро', comment: 'Маленький, але зручний', rating: 4 },
    ],
    availableDates: ['2024-11-26', '2024-11-27', '2024-11-28'],
  },
  {
    id: 4,
    name: 'Сімейний номер',
    description:
      'Ідеально для сімейного відпочинку з двома спальнями і окремою ванною.',
    pricePerNight: 3000,
    maxGuests: 5,
    amenities: ['Wi-Fi', 'Дитяче ліжечко', 'Телевізор', 'Кондиціонер', 'Кухня'],
    images: ['room4.jpg'],
    availability: true,
    rating: 4.6,
    reviews: [
      { user: 'Олена', comment: 'Зручно для всієї родини', rating: 5 },
      { user: 'Андрій', comment: 'Є все, що потрібно для дітей', rating: 5 },
    ],
    availableDates: ['2024-11-24', '2024-11-28', '2024-11-29'],
  },
  {
    id: 5,
    name: 'Делюкс',
    description: 'Ексклюзивний номер з панорамним видом і преміум-зручностями.',
    pricePerNight: 5000,
    maxGuests: 3,
    amenities: ['Wi-Fi', 'Балкон', 'Джакузі', 'Телевізор', 'Сейф'],
    images: ['room5.jpg'],
    availability: false,
    rating: 4.9,
    reviews: [
      { user: 'Валентина', comment: 'Шикарний номер!', rating: 5 },
      {
        user: 'Олексій',
        comment: 'Це найкращий номер, у якому я був',
        rating: 5,
      },
    ],
    availableDates: [], // Немає доступних дат
  },
  {
    id: 6,
    name: 'Стандартний номер з двома ліжками',
    description: 'Простий номер для ділових поїздок або друзів.',
    pricePerNight: 1100,
    maxGuests: 2,
    amenities: ['Wi-Fi', 'Телевізор', 'Кондиціонер'],
    images: ['room6.jpg'],
    availability: true,
    rating: 4.2,
    reviews: [
      { user: 'Наталія', comment: 'Зручні ліжка і чистота', rating: 4 },
      { user: 'Сергій', comment: 'Добре для короткого перебування', rating: 4 },
    ],
    availableDates: ['2024-11-23', '2024-11-24', '2024-11-25', '2024-11-27'],
  },
  {
    id: 7,
    name: 'Лофт',
    description: 'Стильний номер у сучасному стилі для молодіжного відпочинку.',
    pricePerNight: 2000,
    maxGuests: 2,
    amenities: ['Wi-Fi', 'Телевізор', 'Балкон', 'Кухня'],
    images: ['room7.jpg'],
    availability: true,
    rating: 4.7,
    reviews: [
      { user: 'Вікторія', comment: 'Дуже сучасний інтер’єр!', rating: 5 },
      { user: 'Максим', comment: 'Все на найвищому рівні', rating: 5 },
    ],
    availableDates: ['2024-11-24', '2024-11-26', '2024-11-28'],
  },
  {
    id: 8,
    name: 'Студія',
    description: 'Просторий номер зі зручною зоною для роботи і відпочинку.',
    pricePerNight: 1800,
    maxGuests: 3,
    amenities: ['Wi-Fi', 'Телевізор', 'Кондиціонер', 'Робочий стіл'],
    images: ['room8.jpg'],
    availability: true,
    rating: 4.4,
    reviews: [
      { user: 'Софія', comment: 'Зручно для роботи', rating: 4 },
      { user: 'Іван', comment: 'Зручне розташування', rating: 5 },
    ],
    availableDates: ['2024-11-25', '2024-11-26', '2024-11-30'],
  },
  {
    id: 9,
    name: 'Номер для молодят',
    description:
      'Романтичний номер для молодят з окремою ванною і шампанським.',
    pricePerNight: 4000,
    maxGuests: 2,
    amenities: ['Wi-Fi', 'Балкон', 'Джакузі', 'Шампанське'],
    images: ['room9.jpg'],
    availability: false,
    rating: 4.9,
    reviews: [
      { user: 'Тетяна', comment: 'Ідеально для нашої подорожі', rating: 5 },
      { user: 'Юрій', comment: 'Романтична атмосфера', rating: 5 },
    ],
    availableDates: [], // Немає доступних дат
  },
  {
    id: 10,
    name: 'Вілла',
    description: 'Окрема вілла для великої компанії з басейном і кухнею.',
    pricePerNight: 10000,
    maxGuests: 8,
    amenities: ['Wi-Fi', 'Кухня', 'Басейн', 'Парковка'],
    images: ['room10.jpg'],
    availability: true,
    rating: 5.0,
    reviews: [
      { user: 'Олег', comment: 'Це було незабутньо!', rating: 5 },
      {
        user: 'Катерина',
        comment: 'Дуже комфортно для великої компанії',
        rating: 5,
      },
    ],
    availableDates: ['2024-11-23', '2024-11-25', '2024-11-29'],
  },
];
